CREATE TABLE ADVENTUREWORKS2019.DM_ADDRESS (
    NK_ADDRESS INT NOT NULL,
    DS_ADDRESS NVARCHAR(255) NOT NULL,
    DS_CITY NVARCHAR(255) NOT NULL,
    DS_STATE NVARCHAR(50) NOT NULL,
    SG_STATE NVARCHAR(10) NOT NULL,
    DS_COUNTRY NVARCHAR(50) NOT NULL,
    DT_UPDATE_A DATETIME NOT NULL,
    DT_UPDATE_SP DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
    PRIMARY KEY (NK_ADDRESS)
);

SELECT 
    -1 AS NK_ADDRESS, 
    'NO ADDRESS' AS DS_ADDRESS, 
    'NO CITY' AS DS_CITY, 
    'NO STATE' AS DS_STATE,
    'NO STATE COD' AS SG_STATE, 
    'NO COUNTRY' AS DS_COUNTRY,
    CURRENT_TIMESTAMP() AS DT_UPDATE_A,
    CURRENT_TIMESTAMP() AS DT_UPDATE_SP,
    CURRENT_TIMESTAMP() AS DT_CARGA
UNION ALL
SELECT 
    ADDRESSID AS NK_ADDRESS, 
    ADDRESSLINE1 AS DS_ADDRESS, 
    CITY AS DS_CITY, 
    SP.NAME AS DS_STATE,
    STATEPROVINCECODE AS SG_STATE, 
    COUNTRYREGIONCODE AS DS_COUNTRY,
    A.MODIFIEDDATE AS DT_UPDATE_A,
    SP.MODIFIEDDATE AS DT_UPDATE_SP,
    CURRENT_TIMESTAMP() AS DT_CARGA
FROM 
    PERSON.ADDRESS A
LEFT JOIN 
    PERSON.STATEPROVINCE SP ON A.STATEPROVINCEID = SP.STATEPROVINCEID
WHERE 
    1=1;
