CREATE TABLE SALES.DM_CUSTOMER (
    NK_CUSTOMER INT NOT NULL, 
	DS_TYPE	NVARCHAR(255) NOT NULL,
    DS_FIRSTNAME NVARCHAR(255) NOT NULL,
    DS_LASTNAME NVARCHAR(255) NOT NULL,
	DS_STORENAME NVARCHAR(255) NOT NULL,
	DS_PHONE NVARCHAR(255),
	DS_EMAIL NVARCHAR(255),
    DT_REGUPDATE_BE DATETIME,
    DT_REGUPDATE_C DATETIME,
    DT_REGUPDATE_P DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

SELECT
    -1 AS NK_CUSTOMER,
    'NO TYPE' AS DS_TYPE,
    'NO FIRST NAME' AS DS_FIRSTNAME,
    'NO LAST NAME' AS DS_LASTNAME,
    'NO STORE NAME' AS DS_STORENAME,
    'NO PHONE' AS DS_PHONE,
    'NO E-MAIL' AS DS_EMAIL,
    NOW() AS DT_REGUPDATE_BE,
    NOW() AS DT_REGUPDATE_C,
    NOW() AS DT_REGUPDATE_P,
    NOW() AS DT_CARGA
UNION ALL
SELECT
    C.CUSTOMERID AS NK_CUSTOMER,
    IFNULL(PT.DS_TYPE, 'STORE') AS DS_TYPE,
    IFNULL(FIRSTNAME, 'NOT APPLIED') AS DS_FIRSTNAME,
    IFNULL(LASTNAME, 'NOT APPLIED') AS DS_LASTNAME,
    IFNULL(S.NAME, 'NOT APPLIED') AS DS_STORENAME,
    PP.PHONENUMBER AS DS_PHONE,
    EA.EMAILADDRESS AS DS_EMAIL,
    BE.MODIFIEDDATE AS DT_REGUPDATE_BE,
    C.MODIFIEDDATE AS DT_REGUPDATE_C,
    P.MODIFIEDDATE AS DT_REGUPDATE_P,
    NOW() AS DT_CARGA
FROM
    (SELECT 
	CUSTOMERID,
    IF(PERSONID IS NULL, STOREID, PERSONID) AS BUSINESSENTITYID,
    MODIFIEDDATE
	FROM SALES.CUSTOMER
    ) C
JOIN
    PERSON.BUSINESSENTITY BE ON C.BUSINESSENTITYID = BE.BUSINESSENTITYID
LEFT JOIN
    PERSON.PERSON P ON C.BUSINESSENTITYID = P.BUSINESSENTITYID
LEFT JOIN
    SALES.STORE S ON C.BUSINESSENTITYID = S.BUSINESSENTITYID
LEFT JOIN
    PERSON.PERSONPHONE PP ON C.BUSINESSENTITYID = PP.BUSINESSENTITYID
LEFT JOIN
    PERSON.EMAILADDRESS EA ON C.BUSINESSENTITYID = EA.BUSINESSENTITYID
LEFT JOIN
    (SELECT 'SC' AS PERSONTYPE, 'STORE CONTACT' AS DS_TYPE UNION ALL
    SELECT 'IN' AS PERSONTYPE, 'INDIVIDUAL' AS DS_TYPE UNION ALL
    SELECT 'SP' AS PERSONTYPE, 'SALES PERSON' AS DS_TYPE UNION ALL
    SELECT 'EM' AS PERSONTYPE, 'EMPLOYEE' AS DS_TYPE UNION ALL
    SELECT 'VC' AS PERSONTYPE, 'VENDOR' AS DS_TYPE UNION ALL
    SELECT 'GC' AS PERSONTYPE, 'GENERAL CONTACT' AS DS_TYPE
    ) PT ON P.PERSONTYPE = PT.PERSONTYPE
WHERE
    1=1;