CREATE TABLE SALES.DM_PRODUCT (
    NK_PRODUCT INT NOT NULL,
    DS_PRODUCT NVARCHAR(255) NOT NULL,
    DS_COLOR NVARCHAR(50) NOT NULL,
    VL_STDCOST DECIMAL(18,2) NOT NULL,
    VL_SLGPRICE DECIMAL(18,2) NOT NULL,
    DS_SIZE NVARCHAR(50) NOT NULL,
    NR_DAYSMANUFACTURE INT NOT NULL,
    DS_PRODUCTLINE NVARCHAR(255) NOT NULL,
    DT_SELLSTART INT(8) NOT NULL,
    DT_SELLEND INT(8) NOT NULL,
    DT_DISCONTINUED INT(8) NOT NULL,
    DT_REGUPDATE DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

SELECT
    -1 AS NK_PRODUCT,
    'NO PRODUCT' AS DS_PRODUCT,
    'NO COLOR' AS DS_COLOR,
    0.00 AS VL_STDCOST,
    0.00 AS VL_SLGPRICE,
    'NO SIZE' AS DS_SIZE,
    0 AS NR_DAYSMANUFACTURE,
    'NO PRODUCT LINE' AS DS_PRODUCTLINE,
    REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(NOW(), '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS DT_SELLSTART,
    REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(NOW(), '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS DT_SELLEND,
    REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(NOW(), '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS DT_DISCONTINUED,
    NOW() AS DT_REGUPDATE,
    NOW() AS DT_CARGA

UNION ALL

SELECT
    P.PRODUCTID AS NK_PRODUCT,
    P.NAME AS DS_PRODUCT,
    CASE 
        WHEN P.COLOR IS NOT NULL THEN P.COLOR 
        ELSE 
            CASE 
                WHEN P.NAME LIKE '% BLUE%' THEN 'BLUE' 
                WHEN P.NAME LIKE '% RED%' THEN 'RED' 
                WHEN P.NAME LIKE '% SILVER%' THEN 'SILVER' 
                WHEN P.NAME LIKE '% YELLOW%' THEN 'YELLOW' 
                WHEN P.NAME LIKE '% BLACK%' THEN 'BLACK' 
                ELSE 'STANDARD' 
            END 
    END AS DS_COLOR,
    P.STANDARDCOST AS VL_STDCOST,
    P.LISTPRICE AS VL_SLGPRICE,
    CASE 
        WHEN P.SIZE IS NULL THEN 'STANDARD' 
        ELSE P.SIZE 
    END AS DS_SIZE,
    P.DAYSTOMANUFACTURE AS NR_DAYSMANUFACTURE,
    CASE 
        WHEN P.PRODUCTLINE IS NOT NULL THEN P.PRODUCTLINE 
        ELSE 
            CASE 
                WHEN P.PRODUCTLINE = 'R' THEN 'ROAD' 
                WHEN P.PRODUCTLINE = 'M' THEN 'MOUNTAIN' 
                WHEN P.PRODUCTLINE = 'T' THEN 'TOURING' 
                ELSE 'STANDARD' 
            END 
    END AS DS_PRODUCTLINE,
    REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(SELLSTARTDATE, '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS DT_SELLSTART,
    CASE 
        WHEN SELLENDDATE IS NULL THEN -1 
        ELSE REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(SELLENDDATE, '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') 
    END AS DT_SELLEND,
    CASE 
        WHEN DISCONTINUEDDATE IS NULL THEN -1 
        ELSE REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(DISCONTINUEDDATE, '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') 
    END AS DT_DISCONTINUED,
    P.MODIFIEDDATE AS DT_REGUPDATE,
    NOW() AS DT_CARGA

FROM
    PRODUCTION.PRODUCT P

WHERE
    1=1
--      AND CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)
