CREATE TABLE ADVENTUREWORKS2019.DM_PROMOTION (
    NK_PROMOTION INT NOT NULL,
    DS_PROMOTION NVARCHAR(255) NOT NULL,
    RL_DISCOUNT DECIMAL(18,2) NOT NULL,
    DS_TYPE NVARCHAR(50) NOT NULL,
    NR_MINQT INT NOT NULL,
    NR_MAXQT INT NOT NULL,
    DT_START INT(8) NOT NULL,
    DT_END INT(8) NOT NULL,
    DT_REGUPDATE DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

SELECT
    -1 AS NK_PROMOTION,
    'NO PROMOTION' AS DS_PROMOTION,
    0.00 AS RL_DISCOUNT,
    'NO TYPE' AS DS_TYPE,
    0 AS NR_MINQT,
    0 AS NR_MAXQT,
    CURRENT_TIMESTAMP() AS DT_REGUPDATE,
    CAST(REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(NOW(), '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS UNSIGNED) AS DT_START,
    CAST(REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(NOW(), '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS UNSIGNED) AS DT_END,
    CURRENT_TIMESTAMP() AS DT_CARGA

UNION ALL

SELECT
    SPECIALOFFERID AS NK_PROMOTION,
    DESCRIPTION AS DS_PROMOTION,
    DISCOUNTPCT AS RL_DISCOUNT,
    TYPE AS DS_TYPE,
    MINQTY AS NR_MINQT,
    IF(MAXQTY IS NULL, 0, MAXQTY) AS NR_MAXQT,
    MODIFIEDDATE AS DT_REGUPDATE,
    CAST(REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(STARTDATE, '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS UNSIGNED) AS DT_START,
    CAST(REPLACE(REPLACE(REPLACE(CAST(DATE_FORMAT(ENDDATE, '%Y-%m-%d') AS CHAR), ':', ''), '/', ''), '-', '') AS UNSIGNED) AS DT_END,
    CURRENT_TIMESTAMP() AS DT_CARGA
FROM
    SALES.SPECIALOFFER SO
WHERE
    1=1;
--      AND MODIFIEDDATE >= NOW() - INTERVAL 7 DAY;
