CREATE TABLE SALES.DM_SALESPERSON (
    NK_SALESPERSON INT NOT NULL,
    DS_FIRSTNAME NVARCHAR(255) NOT NULL,
    DS_LASTNAME NVARCHAR(255) NOT NULL,
    DS_EMAIL NVARCHAR(255) NOT NULL,
    DT_REGUPDATE_BE DATETIME NOT NULL,
    DT_REGUPDATE_SP DATETIME NOT NULL,
    DT_REGUPDATE_P DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

SELECT 
    '-1' AS NK_SALESPERSON,
    'NO FIRST NAME' AS DS_FIRSTNAME,
    'NO LAST NAME' AS DS_LASTNAME,
    'NO EMAIL' AS DS_EMAIL,
    CURRENT_TIMESTAMP() AS DT_REGUPDATE_BE,
    CURRENT_TIMESTAMP() AS DT_REGUPDATE_SP,
    CURRENT_TIMESTAMP() AS DT_REGUPDATE_P,
    CURRENT_TIMESTAMP() AS DT_CARGA

UNION ALL

SELECT 
    BE.BUSINESSENTITYID AS NK_SALESPERSON,
    FIRSTNAME AS DS_FIRSTNAME,
    LASTNAME AS DS_LASTNAME,
    EA.EMAILADDRESS AS DS_EMAIL,
    BE.MODIFIEDDATE AS DT_REGUPDATE_BE,
    SP.MODIFIEDDATE AS DT_REGUPDATE_SP,
    P.MODIFIEDDATE AS DT_REGUPDATE_P,
    CURRENT_TIMESTAMP() AS DT_CARGA
FROM 
    PERSON.BUSINESSENTITY BE
LEFT JOIN 
    SALES.SALESPERSON SP ON BE.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN 
    PERSON.PERSON P ON BE.BUSINESSENTITYID = P.BUSINESSENTITYID
LEFT JOIN 
    PERSON.EMAILADDRESS EA ON BE.BUSINESSENTITYID = EA.BUSINESSENTITYID
WHERE 
    1=1
    AND P.PERSONTYPE = 'SP';
--    AND MODIFIEDDATE >= NOW() - INTERVAL 7 DAY;
