USE DW_ADVWORKS;
CREATE TABLE ADVENTUREWORKS2019.DM_TIME (
    SK_DATE NUMERIC(8) NOT NULL PRIMARY KEY,
    DT_DATE DATE NOT NULL UNIQUE,
    NR_YEAR INT NOT NULL,
    NR_QUARTER INT NOT NULL,
    NR_MONTH INT NOT NULL,
    NR_DAY INT NOT NULL,
    NR_DAYOFWEEK INT NOT NULL,
    DS_DAY NVARCHAR(50) NOT NULL,
    DS_MONTH NVARCHAR(50) NOT NULL
);


SELECT	CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,DATE)),':-/ ','____'),'_','')) AS SK_DATE,
		DATE AS DT_DATE,
		YEAR(DATE) AS NR_YEAR,
		DATEPART(QUARTER, DATE) AS NR_QUARTER,
		MONTH(DATE) AS NR_MONTH,
		DAY(DATE) AS NR_DAY,
		DATEPART(WEEKDAY, DATE) AS NR_DAYOFWEEK,
		DATENAME(WEEKDAY, DATE) AS DS_DAY,
		DATENAME(MONTH, DATE) AS DS_MONTH
FROM	(SELECT
		DATEADD(DAY, NUMBER, '2010-01-01') AS DATE
		FROM
        MASTER.DBO.SPT_VALUES
		WHERE
        TYPE = 'P' AND NUMBER <= DATEDIFF(DAY, '2010-01-01', '2015-12-31')
		) AS DATERANGE
